info:
  title: Hello World
  version: 1.0.0
swagger: '2.0'
paths:
  /login:
    post:
      description: Login to the application
      produces:
        - application/json
      parameters:
        - name: username
          description: Username to use for login.
          in: formData
          required: true
          type: string
        - name: password
          description: User's password.
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: login
definitions: {}
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
